"""initial schema

Revision ID: 596a0b2597c1
Revises: 
Create Date: 2026-10-03 16:15:33.470378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596a0b2597c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('anomaly_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('detector', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_anomaly_type'), 'anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    op.create_index(op.f('ix_anomalies_run_id'), 'anomalies', ['run_id'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.create_index(op.f('ix_anomalies_status'), 'anomalies', ['status'], unique=False)
    op.create_index('ix_anomalies_status_severity', 'anomalies', ['status', 'severity'], unique=False)
    op.create_index(op.f('ix_anomalies_transaction_id'), 'anomalies', ['transaction_id'], unique=False)
    op.create_index('ix_anomalies_txn_type', 'anomalies', ['transaction_id', 'anomaly_type'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_statement_id', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('counterparty', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('value_date', sa.DateTime(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('amount_base', sa.Float(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=True),
    sa.Column('fx_rate_used', sa.Float(), nullable=True),
    sa.Column('normalized_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_batch_id', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bank_base_amount_date', 'bank_transactions', ['amount_base', 'value_date'], unique=False)
    op.create_index('ix_bank_status_date', 'bank_transactions', ['status', 'value_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_amount_base'), 'bank_transactions', ['amount_base'], unique=False)
    op.create_index(op.f('ix_bank_transactions_bank_statement_id'), 'bank_transactions', ['bank_statement_id'], unique=True)
    op.create_index(op.f('ix_bank_transactions_currency'), 'bank_transactions', ['currency'], unique=False)
    op.create_index(op.f('ix_bank_transactions_id'), 'bank_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_reference_number'), 'bank_transactions', ['reference_number'], unique=False)
    op.create_index(op.f('ix_bank_transactions_source'), 'bank_transactions', ['source'], unique=False)
    op.create_index(op.f('ix_bank_transactions_source_batch_id'), 'bank_transactions', ['source_batch_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_status'), 'bank_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_bank_transactions_value_date'), 'bank_transactions', ['value_date'], unique=False)
    op.create_table('cash_flow_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('predicted_amount', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('inflow', sa.Float(), nullable=True),
    sa.Column('outflow', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('history_days', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flow_forecasts_created_at'), 'cash_flow_forecasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_cash_flow_forecasts_forecast_date'), 'cash_flow_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_cash_flow_forecasts_generated_at'), 'cash_flow_forecasts', ['generated_at'], unique=False)
    op.create_index(op.f('ix_cash_flow_forecasts_id'), 'cash_flow_forecasts', ['id'], unique=False)
    op.create_table('erp_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erp_id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('customer_vendor_name', sa.String(), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('posting_date', sa.DateTime(), nullable=True),
    sa.Column('ledger_account', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('amount_base', sa.Float(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=True),
    sa.Column('fx_rate_used', sa.Float(), nullable=True),
    sa.Column('normalized_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_batch_id', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_erp_base_amount_date', 'erp_records', ['amount_base', 'posting_date'], unique=False)
    op.create_index(op.f('ix_erp_records_amount_base'), 'erp_records', ['amount_base'], unique=False)
    op.create_index(op.f('ix_erp_records_currency'), 'erp_records', ['currency'], unique=False)
    op.create_index(op.f('ix_erp_records_erp_id'), 'erp_records', ['erp_id'], unique=True)
    op.create_index(op.f('ix_erp_records_id'), 'erp_records', ['id'], unique=False)
    op.create_index(op.f('ix_erp_records_invoice_number'), 'erp_records', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_erp_records_posting_date'), 'erp_records', ['posting_date'], unique=False)
    op.create_index(op.f('ix_erp_records_source'), 'erp_records', ['source'], unique=False)
    op.create_index(op.f('ix_erp_records_source_batch_id'), 'erp_records', ['source_batch_id'], unique=False)
    op.create_index(op.f('ix_erp_records_status'), 'erp_records', ['status'], unique=False)
    op.create_index('ix_erp_status_date', 'erp_records', ['status', 'posting_date'], unique=False)
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(), nullable=False),
    sa.Column('to_currency', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_rates_from_currency'), 'fx_rates', ['from_currency'], unique=False)
    op.create_index(op.f('ix_fx_rates_id'), 'fx_rates', ['id'], unique=False)
    op.create_index('ix_fx_rates_pair_valid', 'fx_rates', ['from_currency', 'to_currency', 'valid_to'], unique=False)
    op.create_index(op.f('ix_fx_rates_to_currency'), 'fx_rates', ['to_currency'], unique=False)
    op.create_index(op.f('ix_fx_rates_valid_from'), 'fx_rates', ['valid_from'], unique=False)
    op.create_index(op.f('ix_fx_rates_valid_to'), 'fx_rates', ['valid_to'], unique=False)
    op.create_table('manual_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('ledger_id', sa.String(), nullable=False),
    sa.Column('ledger_type', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_matches_id'), 'manual_matches', ['id'], unique=False)
    op.create_index(op.f('ix_manual_matches_transaction_id'), 'manual_matches', ['transaction_id'], unique=True)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trigger', sa.String(), nullable=True),
    sa.Column('transactions_examined', sa.Integer(), nullable=True),
    sa.Column('candidates_evaluated', sa.Integer(), nullable=True),
    sa.Column('matched_count', sa.Integer(), nullable=True),
    sa.Column('partial_count', sa.Integer(), nullable=True),
    sa.Column('unmatched_count', sa.Integer(), nullable=True),
    sa.Column('flagged_count', sa.Integer(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=True),
    sa.Column('manual_overrides_applied', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_id'), 'reconciliation_runs', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_started_at'), 'reconciliation_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_status'), 'reconciliation_runs', ['status'], unique=False)
    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('ledger_id', sa.String(), nullable=True),
    sa.Column('ledger_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('amount_difference', sa.Float(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_tier', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('score_amount', sa.Float(), nullable=True),
    sa.Column('score_name', sa.Float(), nullable=True),
    sa.Column('score_reference', sa.Float(), nullable=True),
    sa.Column('score_date', sa.Float(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=True),
    sa.Column('transaction_amount_base', sa.Float(), nullable=True),
    sa.Column('ledger_amount_base', sa.Float(), nullable=True),
    sa.Column('date_difference_days', sa.Float(), nullable=True),
    sa.Column('is_manual', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliations_confidence_tier'), 'reconciliations', ['confidence_tier'], unique=False)
    op.create_index(op.f('ix_reconciliations_id'), 'reconciliations', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliations_ledger_id'), 'reconciliations', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_reconciliations_status'), 'reconciliations', ['status'], unique=False)
    op.create_index('ix_reconciliations_status_tier', 'reconciliations', ['status', 'confidence_tier'], unique=False)
    op.create_index(op.f('ix_reconciliations_transaction_id'), 'reconciliations', ['transaction_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('payer', sa.String(), nullable=False),
    sa.Column('payee', sa.String(), nullable=False),
    sa.Column('payer_fsp', sa.String(), nullable=False),
    sa.Column('payee_fsp', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('transfer_state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('amount_base', sa.Float(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=True),
    sa.Column('fx_rate_used', sa.Float(), nullable=True),
    sa.Column('normalized_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_batch_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_amount_base'), 'transactions', ['amount_base'], unique=False)
    op.create_index('ix_transactions_base_amount_date', 'transactions', ['amount_base', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_currency'), 'transactions', ['currency'], unique=False)
    op.create_index('ix_transactions_currency_created', 'transactions', ['currency', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_transactions_reference_id'), 'transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_transactions_source'), 'transactions', ['source'], unique=False)
    op.create_index(op.f('ix_transactions_source_batch_id'), 'transactions', ['source_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_batch_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index('ix_transactions_currency_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_currency'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index('ix_transactions_base_amount_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_amount_base'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_reconciliations_transaction_id'), table_name='reconciliations')
    op.drop_index('ix_reconciliations_status_tier', table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_status'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_ledger_id'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_id'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_confidence_tier'), table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_reconciliation_runs_status'), table_name='reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_runs_started_at'), table_name='reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_runs_id'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_manual_matches_transaction_id'), table_name='manual_matches')
    op.drop_index(op.f('ix_manual_matches_id'), table_name='manual_matches')
    op.drop_table('manual_matches')
    op.drop_index(op.f('ix_fx_rates_valid_to'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_valid_from'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_to_currency'), table_name='fx_rates')
    op.drop_index('ix_fx_rates_pair_valid', table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_id'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_from_currency'), table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_index('ix_erp_status_date', table_name='erp_records')
    op.drop_index(op.f('ix_erp_records_status'), table_name='erp_records')
    op.drop_index(op.f('ix_erp_records_source_batch_id'), table_name='erp_records')
    op.drop_index(op.f('ix_erp_records_source'), table_name='erp_records')
    op.drop_index(op.f('ix_erp_records_posting_date'), table_name='erp_records')
    op.drop_index(op.f('ix_erp_records_invoice_number'), table_name='erp_records')
    op.drop_index(op.f('ix_erp_records_id'), table_name='erp_records')
    op.drop_index(op.f('ix_erp_records_erp_id'), table_name='erp_records')
    op.drop_index(op.f('ix_erp_records_currency'), table_name='erp_records')
    op.drop_index(op.f('ix_erp_records_amount_base'), table_name='erp_records')
    op.drop_index('ix_erp_base_amount_date', table_name='erp_records')
    op.drop_table('erp_records')
    op.drop_index(op.f('ix_cash_flow_forecasts_id'), table_name='cash_flow_forecasts')
    op.drop_index(op.f('ix_cash_flow_forecasts_generated_at'), table_name='cash_flow_forecasts')
    op.drop_index(op.f('ix_cash_flow_forecasts_forecast_date'), table_name='cash_flow_forecasts')
    op.drop_index(op.f('ix_cash_flow_forecasts_created_at'), table_name='cash_flow_forecasts')
    op.drop_table('cash_flow_forecasts')
    op.drop_index(op.f('ix_bank_transactions_value_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_status'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_source_batch_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_source'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_reference_number'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_currency'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_statement_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_amount_base'), table_name='bank_transactions')
    op.drop_index('ix_bank_status_date', table_name='bank_transactions')
    op.drop_index('ix_bank_base_amount_date', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index('ix_anomalies_txn_type', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_transaction_id'), table_name='anomalies')
    op.drop_index('ix_anomalies_status_severity', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_status'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_run_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_type'), table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
