"""settlement windows and run scoping

Revision ID: 77a9a48e8b3e
Revises: 596a0b2597c1
Create Date: 2026-10-03 16:28:30.548652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a9a48e8b3e'
down_revision: Union[str, Sequence[str], None] = '596a0b2597c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlement_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('changed_date', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('transactions_in_window', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_windows_changed_date'), 'settlement_windows', ['changed_date'], unique=False)
    op.create_index(op.f('ix_settlement_windows_created_date'), 'settlement_windows', ['created_date'], unique=False)
    op.create_index(op.f('ix_settlement_windows_id'), 'settlement_windows', ['id'], unique=False)
    op.create_index(op.f('ix_settlement_windows_last_run_id'), 'settlement_windows', ['last_run_id'], unique=False)
    op.create_index(op.f('ix_settlement_windows_reconciled_at'), 'settlement_windows', ['reconciled_at'], unique=False)
    op.create_index(op.f('ix_settlement_windows_state'), 'settlement_windows', ['state'], unique=False)
    op.create_index('ix_settlement_windows_state_changed', 'settlement_windows', ['state', 'changed_date'], unique=False)
    op.create_index(op.f('ix_settlement_windows_synced_at'), 'settlement_windows', ['synced_at'], unique=False)
    op.create_index(op.f('ix_settlement_windows_window_id'), 'settlement_windows', ['window_id'], unique=True)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('settlement_model', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('changed_date', sa.DateTime(), nullable=True),
    sa.Column('window_ids', sa.Text(), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_created_date'), 'settlements', ['created_date'], unique=False)
    op.create_index(op.f('ix_settlements_id'), 'settlements', ['id'], unique=False)
    op.create_index(op.f('ix_settlements_settlement_id'), 'settlements', ['settlement_id'], unique=True)
    op.create_index(op.f('ix_settlements_state'), 'settlements', ['state'], unique=False)
    op.add_column('reconciliation_runs', sa.Column('scope', sa.String(), nullable=True))
    op.add_column('reconciliation_runs', sa.Column('settlement_window_id', sa.String(), nullable=True))
    op.add_column('reconciliation_runs', sa.Column('scope_from', sa.DateTime(), nullable=True))
    op.add_column('reconciliation_runs', sa.Column('scope_to', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_reconciliation_runs_scope'), 'reconciliation_runs', ['scope'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_settlement_window_id'), 'reconciliation_runs', ['settlement_window_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_runs_settlement_window_id'), table_name='reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_runs_scope'), table_name='reconciliation_runs')
    op.drop_column('reconciliation_runs', 'scope_to')
    op.drop_column('reconciliation_runs', 'scope_from')
    op.drop_column('reconciliation_runs', 'settlement_window_id')
    op.drop_column('reconciliation_runs', 'scope')
    op.drop_index(op.f('ix_settlements_state'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_settlement_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_created_date'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_settlement_windows_window_id'), table_name='settlement_windows')
    op.drop_index(op.f('ix_settlement_windows_synced_at'), table_name='settlement_windows')
    op.drop_index('ix_settlement_windows_state_changed', table_name='settlement_windows')
    op.drop_index(op.f('ix_settlement_windows_state'), table_name='settlement_windows')
    op.drop_index(op.f('ix_settlement_windows_reconciled_at'), table_name='settlement_windows')
    op.drop_index(op.f('ix_settlement_windows_last_run_id'), table_name='settlement_windows')
    op.drop_index(op.f('ix_settlement_windows_id'), table_name='settlement_windows')
    op.drop_index(op.f('ix_settlement_windows_created_date'), table_name='settlement_windows')
    op.drop_index(op.f('ix_settlement_windows_changed_date'), table_name='settlement_windows')
    op.drop_table('settlement_windows')
    # ### end Alembic commands ###
